version: '2.3' # specify docker-compose version

# Define the services/containers to be run
services:
  angular:
    hostname: localhost
    #container_name: angular-app
    build:
      context: .
      dockerfile: angular-app/Dockerfile
    links:
      - express
    volumes:
      - ".:/app"
    tty: false
    ports:
      - 8181:4200
      - 4400:49153
  express: #name of the second service
    build:
      context: .
      dockerfile: express-server/Dockerfile
    links:
      - database
    volumes:
       - ".:/app"
    tty: false
    ports:
      - "3000:3000" #specify ports forewarding

  database: # name of the third service
    image: mongo # specify image to build container from
    ports:
      - "27017:27017" # specify port forewarding
